# Generated by Django 3.2 on 2023-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='imagini/'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
