# Generated by Django 3.2 on 2023-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0002_auto_20230606_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='imagini3/'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='imagini2/'),
        ),
    ]
