# Generated by Django 3.2 on 2023-06-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0003_auto_20230606_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='imagini4/'),
        ),
        migrations.AddField(
            model_name='casa',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='imagini5/'),
        ),
    ]
