# Generated by Django 3.2 on 2023-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0004_auto_20230607_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='numar_telefon',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
