# Generated by Django 3.2 on 2023-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0005_casa_numar_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='image5',
            field=models.ImageField(null=True, upload_to='imagini5/'),
        ),
    ]
