# Generated by Django 3.2 on 2023-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0006_alter_casa_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='imagini5/'),
        ),
    ]
